trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: auc_precision_recall
    maxTrials: 10
    maxParallelTrials: 1
    params:
      - parameterName: first-layer-size
        type: INTEGER
        minValue: 16
        maxValue: 32
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: num-layers
        type: INTEGER
        minValue: 1
        maxValue: 4
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: scale-factor
        type: DOUBLE
        minValue: 0.6
        maxValue: 0.8
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: embedding-size
        type: INTEGER
        minValue: 2
        maxValue: 4
        scaleType: UNIT_LINEAR_SCALE
